apiVersion: v1
kind: ServiceAccount
metadata:
  name: discord-kube-bot
  namespace: discord-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discord-kube-bot-role
  namespace: discord-bot
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discord-kube-bot-binding
  namespace: discord-bot
subjects:
  - kind: ServiceAccount
    name: discord-kube-bot
    namespace: discord-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discord-kube-bot-role
