apiVersion: v1
kind: Secret
metadata:
  name: discord-kube-bot-secrets
  namespace: discord-bot
type: Opaque
stringData:
  DISCORD_TOKEN: "replace-me"
  DISCORD_GUILD_ID: "1491150711000399982"
  DISCORD_ALLOWED_ROLE_IDS: "1491154102607020234"
  KUBE_ALLOWED_NAMESPACES: "argocd,cilium-secrets,clouadfare,csi-proxmox,cv,dasboard,ddos-protection,default,discord-bot,employee-leave,forgejo,forgejo-runner,gaz,immich,kube-node-lease,kube-public,kube-system,monitoring,postgress,todo-app"
  DISCORD_AUDIT_WEBHOOK_URL: "replace-me"
