apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-kube-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pascariucosmin93/discord-boot.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: discord-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
